# Generated by Django 6.0.2 on 2026-03-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.TextField(blank=True, help_text='e.g. Fever, cough (Primary/Secondary care)', null=True),
        ),
    ]
