# Generated by Django 6.0.2 on 2026-03-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_reason_for_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, help_text='Prescribed medicines', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Advice for the patient', null=True),
        ),
    ]
